spring.application.name=auth-service
server.servlet.context-path=/api

service.auth.url=http://localhost:8080

security.jwt.private-key=classpath:private_key.pem
security.jwt.public-key=classpath:public_key.pem