spring.application.name=data-service
server.servlet.context-path=/api
server.port=8081

service.name=data-service
service.secret=data-service-secret
service.auth.url=http://localhost:8080

security.jwt.public-key=classpath:public_key.pem

logging.level.org.springframework.security=DEBUG